# SPDX-FileCopyrightText: 2025 Javier PÃ©rez
#
# SPDX-License-Identifier: CC0-1.0

# This is a reusable workflow to mirror a single branch from a remote git repository to GitHub.

name: Mirror remote repository to GitHub

on:
  workflow_call:
    inputs:
      repository-url:
        description: The HTTPS URL of the source git repository to clone to GitHub.
        type: string
        required: true
      rewrite-lfs:
        description: |
          Whether to convert Git LFS pointer files to their associated blob files, effectively disabling Git LFS in the mirror.
          By default, LFS will be included in the mirror repository.
          Be careful when enabling this option because it may increase the execution time of this workflow significantly.
          There are certain limits on GitHub so it is important to keep LFS disabled on some repositories.
        type: boolean
        required: false
        default: false
      token:
        description: |
          The personal access token used to perform operations.
          Some permissions, such as `workflows`, are only available to PATs and not to the default GITHUB_TOKEN.
        type: string
        required: false
        default: ${{ secrets.GITHUB_TOKEN }}


jobs:
  mirror-remote-repo:
    runs-on: ubuntu-22.04
    steps:
      # Installing Git LFS with apt configures LFS in the system-level git config file (/etc/gitconfig).
      # Therefore, running `git lfs install` is not necessary.
      - name: Download and install Git LFS
        run: |
          apt-get update
          apt-get install --assume-yes git-lfs=3.0.2-1ubuntu0.3

      - name: Clone remote repository
        run: git clone --branch ${{ github.ref }} ${{ inputs.repository-url }} source

      # This will rewrite the git history, it will change the ID of most git objects in the mirror.
      - name: Migrate LFS
        if: ${{ inputs.rewrite-lfs }}
        working-directory: ./source
        run: git lfs migrate export --verbose --include="*" --everything --skip-fetch --yes 2>&1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ inputs.token }}
          branch: ${{ github.ref }}
          force: true
          tags: true
          directory: source
